hombre(jack).
hombre(james).
hombre(bryan).
hombre(louis).
hombre(angel).
hombre(peter).
hombre(paul).
hombre(jose).
hombre(martin).
hombre(richard).
hombre(joseph).
hombre(lee).
hombre(pedro).
hombre(santiago).
hombre(pablo).
hombre(mark).
hombre(juan).
hombre(shun).
hombre(david).


mujer(rose).
mujer(louis).
mujer(alisha).
mujer(namie).
mujer(kiara).
mujer(belen).
mujer(hinamie).
mujer(luz).
mujer(ana).
mujer(kimberly).
mujer(hina).
mujer(nataly).
mujer(luisa).

paisde(peru,america).
paisde(argentina,america).
paisde(mexico,america).
paisde(colombia.america).
paisde(holanda,europa).
paisde(inglaterra,europa).
paisde(irlanda,europa).
paisde(alemania,europa).
paisde(india,asia).
paisde(corea.asia).
paisde(japon,asia).
paisde(china,asia).


origende(jack,holanda).
origende(james,inglaterra).
origende(bryan,españa).
origende(louis,irlanda).
origende(angel,españa).
origende(peter,holanda).
origende(paul,irlanda).
origende(jose,peru).
origende(martin,españa).
origende(richard,holanda).
origende(joseph,inglaterra).
origende(lee,japon).
origende(pedro,mexico).
origende(santiago,mexico).
origende(pablo,colombia).
origende(mark,inglaterra).
origende(juan,argentina).
origende(shun,china).
origende(david,argentina).

origende(rose,alemania).
origende(alisha,india).
origende(namie,corea).
origende(kiara,peru).
origende(belen,argentina).
origende(hinamie,corea).
origende(luz,colombia).
origende(ana,españa).
origende(kimberly,irlanda).
origende(hina,japon).
origende(nataly,colombia).
origende(luisa,peru).

ysuidiomaes(peru,español).
ysuidiomaes(argentina,español).
ysuidiomaes(mexico,español).
ysuidiomaes(colombia.español).
ysuidiomaes(holanda,neerlandes).
ysuidiomaes(inglaterra,ingles).
ysuidiomaes(irlanda,ingles).
ysuidiomaes(alemania,aleman).
ysuidiomaes(india,ingles).
ysuidiomaes(corea.coreano).
ysuidiomaes(japon,japones).
ysuidiomaes(china,chino).

estudio(jack,ingles).
estudio(james,español).
estudio(kiara,ingles).
estudio(angel,ingles).
estudio(nataly,ingles).
estudio(mark,coreano).

progenitor(jack,rose).
progenitor(jack,james).
progenitor(rose,bryan).
progenitor(rose,louis).
progenitor(james,alisha).
progenitor(james,namie).
progenitor(bryan,kiara).
progenitor(bryan,angel).
progenitor(louis,peter).
progenitor(louis,paul).
progenitor(alisha,jose).
progenitor(alisha,belen).
progenitor(namie,hinamie).
progenitor(kiara,luz).
progenitor(angel,martin).
progenitor(angel,ana).
progenitor(peter,richard).
progenitor(peter,joseph).
progenitor(paul,kimberly).
progenitor(jose,hina).
progenitor(jose,lee).
progenitor(belen,pedro).
progenitor(belen,santiago).
progenitor(luz,nataly).
progenitor(luz,pablo).
progenitor(ana,mark).
progenitor(ana,juan).
progenitor(joseph,shun).
progenitor(lee,luisa).
progenitor(pedro,david).
